version: '3'

volumes:
  node_modules:
  vendor:

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/var/www/
      - node_modules:/var/www/node_modules
      - vendor:/var/www/vendor
    ports:
      - 80:80

  db:
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    restart: always
    volumes:
      - ./docker/db/dbdata:/var/lib/postgresql/data
      - ./database/migration:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: '${DB_DATABASE}'

  pgadmin4:
    image: dockage/phppgadmin
    ports:
      - 8080:80
    environment:
      PHP_PG_ADMIN_SERVER_HOST: db

  memcached:
    build:
      context: ./
      dockerfile: ./docker/memcached/Dockerfile
    ports:
      - 11211:11211
